services:
  - type: web
    name: youtube-summarizer
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python web_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /
